### PR TITLE
Make ngModel for hidden input field work with parent scope

### PR DESCRIPTION
**Pull request by Morpho**
It just doesnt work without this..

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
seems legit!
can you add a brief comment to describe why we need those lines?

**Comment by Morpho** [comment]
It's needed because angular-js doesn't do two-way databinding for input[type]=hidden fields: https://github.com/angular/angular.js/pull/2574

**Comment by dmitry-mukhin** [comment]
I was referring co comment in the code)

**Comment by dmitry-mukhin** [comment]
I forgot to thank you, sorry about that.
Thanks!

**Comment by homm** [comment]
@Morpho Could you elaborate where `$parse` and `$attrs` comes from? Should them be declared somewhere?

**Comment by dmitry-mukhin** [comment]
@Morpho @homm I believe that this should help

```
- controller: ['$scope', '$element', '$log', function($scope, $element, $log) {
+ controller: ['$scope', '$element', '$log', '$parse', '$attrs', function($scope, $element, $log, $parse, $attrs) {
```

**Comment by dmitry-mukhin** [comment]
fixed in #9

**Pull request merged**
