### PR TITLE
fix(readme): .full.js is version without jQuery

### PR DESCRIPTION
**Pull request by theaqua**
Sorry, I fix it.

### CODE REVIEW

**Comment by homm** [comment]
But `uploadcare.full.min.js` is version with jquery, not without (current version is right).

**Comment by theaqua** [comment]
I don't think so.

`uploadcare.min.js` throws error, if jQuery isn't defined
image

`uploadcare.full.min.js` works fine.

**Comment by theaqua** [comment]
It also contains `Pusher.js`, but I don't see any reference of it…

**Comment by homm** [comment]
> `uploadcare.full.min.js` works fine.

This is exactly what expected. Because `uploadcare.full.min.js` is version **with** jQuery built-in, while `uploadcare.min.js` is version **without**.

> but I don't see any reference of it…

What references do you mean?

**Comment by theaqua** [comment]
Oh, I see.

About Pusher — nevermind, my mistake. I'm careless today :disappointed:

**Pull request closed without merging**
